# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
- openjdk14

services:
  - postgresql


# Отправлять уведомление на почту laiwiense@gmail.com
notifications:
  email:
    recipients:
      -laiwiense@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

before_install:
  - chmod +x mvnw

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
  - psql -c 'create database job4j_forum;' -U postgres